### ISSUE TITLE
vs-code-pandoctools

### ISSUE THREAD

**Issue by kiwi0fruit** [kiwi0fruit/pandoctools#42]
* [ ] First prepare [this](https://github.com/kiwi0fruit/pandoctools/issues/28)
* [ ] Save file on run, start independent pandoctools CLI
* [ ] Read Pandoctools path from user data

**Comment by kiwi0fruit** [comment]
ARCHIVE:

* ~add [MPP Patch](https://github.com/kiwi0fruit/misc/tree/master/src/mpp) to atom-pandoctools~
* ~[Add font options and other tweakabe css propertiers](https://github.com/atom-community/markdown-preview-plus/issues/441)~
* ~add fonts to atom-pandoctoola [or go another way](https://github.com/braver/fonts/issues/82)~


### ~Fix MPP~

* ~[added api inside styles.less](https://github.com/atom-community/markdown-preview-plus/pull/444)~
* ~[Links don't work in preview](https://github.com/atom-community/markdown-preview-plus/issues/303)~

~[CONTRIBUTING](https://github.com/atom-community/markdown-preview-plus/blob/master/CONTRIBUTING.md)~

* [x] ~[Empty lines in code blocks dissapper](https://github.com/atom-community/markdown-preview-plus/issues/398)~
* ~[Image scaling issues with non-standard PPI OS settings](https://github.com/atom-community/markdown-preview-plus/issues/405)~
* [x] ~[Save As PDF makes font colors darker](https://github.com/atom-community/markdown-preview-plus/issues/393)~
* ~do not forget about [this](https://github.com/kiwi0fruit/misc/commit/70609c253629c09d51dc35076e69755d31d2d869) - add font settings to GUI~
* [x] ~check if code highlighter spaces problem ([nbsp replace font fallback bugfix](https://github.com/atom-haskell/atom-highlights/pull/1)) is solved~
* [x] ~check if `data:image/`now works~
* [x] ~find out how to tune MathJax and tune it~
* ~fix main .less file. Move fonts definitions there too and take into account  changes:
    `.markdown-preview:not([data-use-github-style])` ->  
    `markdown-preview-plus-view:not([data-use-github-style])` changes~
* [x] ~`@mjx-mono-font-size: 80%;`~
* ~enhance PDF print ([PDF print for smartphone/tablet/desktop/A4-printer](https://github.com/atom-community/markdown-preview-plus/issues/397))~
  * ~.pdf.7z~
      * ~.phone.pdf~
      * ~.tablet.pdf~
      * ~.desktop.pdf~
      * ~.A4.pdf~

# ~Later~

~[Reusing MPP in another package / from outside of Atom](https://github.com/atom-community/markdown-preview-plus/issues/322)~

~`~/.atom/styles.less`:~
```less
@import './packages/pandoctools/styles/mpp.less';
// I guess this can be automatical ^^

@main-font: "Libertinus Serif", serif;

.markdown-preview-plus() {
  .pandoctools();
}
```

~`~/.atom/packages/pandoctools/styles/pandoctools.less`:~
```less
@main-font: "Segoe UI", sans-serif;

.pandoctools() {
  .sourceCode {
    background-color: hsl(180, 24%, 90%) !important;
  }
  * {
    color: blue !important;
  }
  body {
    font-family: @main-font;
  }
}

```

~`~/.atom/packages/markdown-preview-plus/styles-client/less-api.less`:~
```less
.markdown-preview-plus() {}
@import (optional, reference) '../../../styles.less';
.markdown-preview-plus();
```

```js
  // if `pandoctools_integration` package option:
  //     if file `api-pandoctools.less` not exists:
  //         create file `api-pandoctools.less` from template
  //         (with abs path to ~/.atom/packages/atom-pandoctools/styles.less)
  //     styles.push(getClientStyle('api-pandoctools.less'))
  // if file `api-styles.less` not exists:
  //     create file `api-styles.less` from template
  //     (with abs path to ~/.atom/styles.less)
  // styles.push(getClientStyle('api-styles.less'))
```

**Comment by kiwi0fruit** [comment]
closed in favor of https://github.com/kiwi0fruit/pandoctools/issues/28
